"""
generated_tool.py - self-authored tool support (Hermes-style)

A GeneratedTool is a BaseTool whose body was written by the model at runtime via
the `create_tool` meta-tool, persisted to disk, and reloaded on startup. The
on-disk package is **hub-installable** from day one (feature I distributes the
exact same folder):

    plugins/generated/<name>/
        tool.py        # `async def run(args, shell): ...` - the model's code
        manifest.json  # name, version, description, parameters (JSON schema),
                       # origin, author, created, last_used, use_count, state,
                       # state_changed, phase, deps, sha256(tool.py)

Trust model: `origin == "self"` tools were written locally by the agent and are
trusted at the same level as the rest of Mapache (which already runs arbitrary
shell). `origin == "hub"` tools are third-party code - their tool.py is verified
against `sha256` in the manifest before it is ever compiled, and a tampered or
unverified hub tool refuses to load.

Lifecycle state lives in the manifest: active -> stale -> archived (see
GeneratedToolManager). Using a stale tool auto-promotes it back to active; that
promotion happens here, in execute(), since this is the one place that knows a
generated tool actually ran.
"""

from __future__ import annotations

import hashlib
import json
import shutil
import traceback
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Optional

from plugins.sdk.base_tool import BaseTool, Permission, ToolResult

MANIFEST_NAME = "manifest.json"
CODE_NAME = "tool.py"

# State machine for the curator. active/stale are both loaded + exposed; archived
# tools are moved out of the load path entirely.
STATE_ACTIVE = "active"
STATE_STALE = "stale"
STATE_ARCHIVED = "archived"

# Where a generated tool may be exposed. "always" = every phase (like MCP tools).
VALID_PHASES = {"recon", "enumeration", "exploitation", "post", "reporting", "always"}

# The shell helper injected into every generated tool's namespace.
ShellFn = Callable[[str], "Any"]  # async (str) -> str


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def sha256_of(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _name_ok(name: str) -> bool:
    """A generated tool name must be a safe, snake_case-ish identifier."""
    import re
    return bool(re.fullmatch(r"[a-z][a-z0-9_]{1,48}", name or ""))


# --------------------------------------------------------------------------- #
# Code template
#
# The model supplies the *body* of run(), not a whole file - local models mangle
# full class/file output, and a fixed contract keeps validation + the hub format
# uniform. We indent the body under a canonical signature so the surface the model
# writes against is always exactly: `args` (dict of validated arguments) and
# `shell` (async callable: await shell("cmd") -> str).
# --------------------------------------------------------------------------- #

_CODE_HEADER = (
    "# Auto-generated by Mapache create_tool. Do not edit by hand.\n"
    "# Contract: async def run(args, shell) -> str\n"
    "#   args  : dict of validated arguments (per the tool's JSON schema)\n"
    "#   shell : async callable, `await shell(\"cmd\")` -> command output string\n"
    "# Return a string; it becomes the tool's output.\n"
)


def render_tool_source(code_body: str) -> str:
    """Wrap a model-supplied body into a compilable `async def run(args, shell)`."""
    body = code_body.replace("\r\n", "\n").rstrip("\n")
    if not body.strip():
        body = 'return "(generated tool did nothing)"'
    indented = "\n".join("    " + line if line.strip() else line
                         for line in body.split("\n"))
    return f"{_CODE_HEADER}\n\nasync def run(args, shell):\n{indented}\n"


def compile_run(source: str, name: str) -> Callable:
    """
    Compile generated source and return its `run` coroutine function.

    Raises SyntaxError if the source does not compile, or ValueError if it does
    not define an `async def run`. Callers surface these back to the model so it
    can self-correct (same philosophy as the reask loop).
    """
    namespace: dict[str, Any] = {}
    compiled = compile(source, f"<generated:{name}>", "exec")
    exec(compiled, namespace)  # noqa: S102 - trusted/self-origin or hub-verified
    run = namespace.get("run")
    if run is None or not callable(run):
        raise ValueError("generated code must define `async def run(args, shell)`")
    return run


# --------------------------------------------------------------------------- #
# GeneratedTool
# --------------------------------------------------------------------------- #


class GeneratedTool(BaseTool):
    """A BaseTool backed by model-authored code + an on-disk manifest."""

    # Placeholder to satisfy BaseTool.__init_subclass__ (which requires a
    # non-empty class-level name). Real names are per-instance, set in __init__.
    name = "generated_tool"
    tags = ["generated"]

    def __init__(
        self,
        tool_dir: Path,
        manifest: dict[str, Any],
        run: Callable,
        shell: Optional[ShellFn] = None,
    ) -> None:
        self.tool_dir = Path(tool_dir)
        self.manifest = manifest
        self._run = run
        self._shell = shell

        # Instance attrs shadow the class placeholders the registry reads.
        self.name = manifest["name"]
        self.description = manifest.get("description", "")
        self.parameters = manifest.get("parameters") or {"type": "object", "properties": {}}
        self.version = manifest.get("version", "0.1.0")
        self.permissions = {Permission.SHELL, Permission.FILESYSTEM}
        self.tags = ["generated", manifest.get("origin", "self")]

    # -- exposure metadata ------------------------------------------------- #

    @property
    def phase(self) -> str:
        return self.manifest.get("phase", "always")

    @property
    def origin(self) -> str:
        return self.manifest.get("origin", "self")

    @property
    def state(self) -> str:
        return self.manifest.get("state", STATE_ACTIVE)

    def set_shell(self, shell: ShellFn) -> None:
        self._shell = shell

    # -- execution --------------------------------------------------------- #

    async def execute(self, **kwargs: Any) -> ToolResult:
        self._record_use()
        try:
            result = await self._run(dict(kwargs), self._shell)
        except Exception:  # generated code must never crash the loop
            tb = traceback.format_exc(limit=4)
            return ToolResult.fail(
                f"generated tool '{self.name}' raised:\n{tb}",
            )
        if isinstance(result, ToolResult):
            return result
        if result is None:
            return ToolResult.ok("(no output)")
        return ToolResult.ok(str(result))

    def _record_use(self) -> None:
        """Bump usage stats and auto-promote a stale tool back to active."""
        try:
            self.manifest["last_used"] = _now_iso()
            self.manifest["use_count"] = int(self.manifest.get("use_count", 0)) + 1
            if self.manifest.get("state") == STATE_STALE:
                self.manifest["state"] = STATE_ACTIVE
                self.manifest["state_changed"] = _now_iso()
            save_manifest(self.tool_dir, self.manifest)
        except Exception:
            pass  # usage tracking is best-effort; never block the tool


# --------------------------------------------------------------------------- #
# Persistence
# --------------------------------------------------------------------------- #


def save_manifest(tool_dir: Path, manifest: dict[str, Any]) -> None:
    (Path(tool_dir) / MANIFEST_NAME).write_text(
        json.dumps(manifest, indent=2), encoding="utf-8"
    )


def load_manifest(tool_dir: Path) -> dict[str, Any]:
    return json.loads((Path(tool_dir) / MANIFEST_NAME).read_text(encoding="utf-8"))


def write_generated_tool(
    base_dir: Path,
    name: str,
    description: str,
    parameters: dict[str, Any],
    code_body: str,
    *,
    origin: str = "self",
    author: str = "mapache-agent",
    phase: str = "always",
    version: str = "0.1.0",
    deps: Optional[list[str]] = None,
) -> Path:
    """
    Write a generated tool package to disk and return its directory.

    Does not register or compile - callers validate + compile first so a bad
    tool never lands on disk.
    """
    tool_dir = Path(base_dir) / name
    tool_dir.mkdir(parents=True, exist_ok=True)

    source = render_tool_source(code_body)
    (tool_dir / CODE_NAME).write_text(source, encoding="utf-8")

    manifest = {
        "name": name,
        "version": version,
        "description": description,
        "parameters": parameters,
        "origin": origin,
        "author": author,
        "created": _now_iso(),
        "last_used": None,
        "use_count": 0,
        "state": STATE_ACTIVE,
        "state_changed": _now_iso(),
        "phase": phase if phase in VALID_PHASES else "always",
        "deps": deps or [],
        "sha256": sha256_of(source),
    }
    save_manifest(tool_dir, manifest)
    return tool_dir


def load_generated_tool(
    tool_dir: Path,
    shell: Optional[ShellFn] = None,
) -> GeneratedTool:
    """
    Load and compile a generated tool package.

    For `origin == "hub"`, the on-disk tool.py is verified against the manifest
    sha256 *before* it is compiled - a tampered or unverified hub tool refuses
    to load. Self-origin tools skip the check (they were written locally).
    """
    tool_dir = Path(tool_dir)
    manifest = load_manifest(tool_dir)
    source = (tool_dir / CODE_NAME).read_text(encoding="utf-8")

    if manifest.get("origin") == "hub":
        expected = manifest.get("sha256")
        actual = sha256_of(source)
        if not expected or expected != actual:
            raise ValueError(
                f"hub tool '{manifest.get('name')}' failed checksum "
                f"(expected {expected}, got {actual}) - refusing to load"
            )

    run = compile_run(source, manifest.get("name", "unknown"))
    return GeneratedTool(tool_dir, manifest, run, shell=shell)


def move_tool_dir(src: Path, dst_parent: Path) -> Path:
    """Move a tool package folder under dst_parent, returning the new path."""
    src = Path(src)
    dst_parent = Path(dst_parent)
    dst_parent.mkdir(parents=True, exist_ok=True)
    dst = dst_parent / src.name
    if dst.exists():
        shutil.rmtree(dst)
    shutil.move(str(src), str(dst))
    return dst
